version: 2.1

jobs:
  publish:
    docker:
      - image: cimg/node:16.11.0
    steps:
      - checkout
      - run: node --version

workflows:
  publish:
    jobs:
      - publish
      # TODO: require test step
      # - publish
      #     requires:
      #       - test
