version: 2.1

jobs:
  publish:
    docker:
      - image: cimg/node:16.10.0
    steps:
      - checkout
      - run: npm ci
      - run: npm run publish

workflows:
  publish:
    jobs:
      - publish
      # TODO: require test step
      # - publish
      #     requires:
      #       - test
