version: 2.1

prelude: &prelude
  docker:
    - image: cimg/node:16.10.0

jobs:
  publish:
    <<: *prelude
    steps:
      - checkout
      - run: npm ci
      # TODO: cache installation with a hash
      - run: npm run publish

workflows:
  publish:
    jobs:
      - manual_approval:
          type: approval
      - publish:
          requires:
            - manual_approval
